//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services_All.PbmS_Member {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/")]
    public partial class DhcTlException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string exceptionDetailsField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string exceptionDetails {
            get {
                return this.exceptionDetailsField;
            }
            set {
                this.exceptionDetailsField = value;
                this.RaisePropertyChanged("exceptionDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/")]
    public partial class feedbackResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        private string mSGField;
        
        private string xmlFileNameField;
        
        private string errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("valueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MSG {
            get {
                return this.mSGField;
            }
            set {
                this.mSGField = value;
                this.RaisePropertyChanged("MSG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string XmlFileName {
            get {
                return this.xmlFileNameField;
            }
            set {
                this.xmlFileNameField = value;
                this.RaisePropertyChanged("XmlFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string errorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
                this.RaisePropertyChanged("errorDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/")]
    public partial class memberExclusion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int gourpIdField;
        
        private bool gourpIdFieldSpecified;
        
        private string memberNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int gourpId {
            get {
                return this.gourpIdField;
            }
            set {
                this.gourpIdField = value;
                this.RaisePropertyChanged("gourpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gourpIdSpecified {
            get {
                return this.gourpIdFieldSpecified;
            }
            set {
                this.gourpIdFieldSpecified = value;
                this.RaisePropertyChanged("gourpIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string memberNo {
            get {
                return this.memberNoField;
            }
            set {
                this.memberNoField = value;
                this.RaisePropertyChanged("memberNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", ConfigurationName="PbmS_Member.MemberUpdateWS")]
    public interface MemberUpdateWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemberExclusionReques" +
            "t", ReplyAction="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemberExclusionRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services_All.PbmS_Member.DhcTlException), Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemberExclusion/Fault" +
            "/DhcTlException", Name="DhcTlException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Services_All.PbmS_Member.updateMemberExclusionResponse updateMemberExclusion(Services_All.PbmS_Member.updateMemberExclusionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemberExclusionReques" +
            "t", ReplyAction="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemberExclusionRespon" +
            "se")]
        System.Threading.Tasks.Task<Services_All.PbmS_Member.updateMemberExclusionResponse> updateMemberExclusionAsync(Services_All.PbmS_Member.updateMemberExclusionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebrBatchRequest", ReplyAction="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebrBatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services_All.PbmS_Member.DhcTlException), Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebrBatch/Fault/Dhc" +
            "TlException", Name="DhcTlException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Services_All.PbmS_Member.updateMemebrBatchResponse updateMemebrBatch(Services_All.PbmS_Member.updateMemebrBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebrBatchRequest", ReplyAction="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebrBatchResponse")]
        System.Threading.Tasks.Task<Services_All.PbmS_Member.updateMemebrBatchResponse> updateMemebrBatchAsync(Services_All.PbmS_Member.updateMemebrBatchRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebrRequest", ReplyAction="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebrResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services_All.PbmS_Member.DhcTlException), Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebr/Fault/DhcTlExc" +
            "eption", Name="DhcTlException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Services_All.PbmS_Member.updateMemebrResponse updateMemebr(Services_All.PbmS_Member.updateMemebrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebrRequest", ReplyAction="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/updateMemebrResponse")]
        System.Threading.Tasks.Task<Services_All.PbmS_Member.updateMemebrResponse> updateMemebrAsync(Services_All.PbmS_Member.updateMemebrRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/getMemberDetailsRequest", ReplyAction="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/getMemberDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services_All.PbmS_Member.DhcTlException), Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/getMemberDetails/Fault/DhcT" +
            "lException", Name="DhcTlException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Services_All.PbmS_Member.getMemberDetailsResponse getMemberDetails(Services_All.PbmS_Member.getMemberDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/getMemberDetailsRequest", ReplyAction="http://memberMgr.ws.bus.dimensions.com/MemberUpdateWS/getMemberDetailsResponse")]
        System.Threading.Tasks.Task<Services_All.PbmS_Member.getMemberDetailsResponse> getMemberDetailsAsync(Services_All.PbmS_Member.getMemberDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMemberExclusion", WrapperNamespace="http://memberMgr.ws.bus.dimensions.com/", IsWrapped=true)]
    public partial class updateMemberExclusionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int payerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("memberExclusionsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services_All.PbmS_Member.memberExclusion[] memberExclusionsList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string registrationKey;
        
        public updateMemberExclusionRequest() {
        }
        
        public updateMemberExclusionRequest(int payerId, Services_All.PbmS_Member.memberExclusion[] memberExclusionsList, string registrationKey) {
            this.payerId = payerId;
            this.memberExclusionsList = memberExclusionsList;
            this.registrationKey = registrationKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMemberExclusionResponse", WrapperNamespace="http://memberMgr.ws.bus.dimensions.com/", IsWrapped=true)]
    public partial class updateMemberExclusionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services_All.PbmS_Member.feedbackResult @return;
        
        public updateMemberExclusionResponse() {
        }
        
        public updateMemberExclusionResponse(Services_All.PbmS_Member.feedbackResult @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/")]
    public partial class memberRecordDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateOfBirthField;
        
        private bool dateOfBirthFieldSpecified;
        
        private string divisionIdField;
        
        private System.DateTime effectiveFromField;
        
        private bool effectiveFromFieldSpecified;
        
        private System.DateTime effectiveToField;
        
        private bool effectiveToFieldSpecified;
        
        private string firstNameField;
        
        private ushort genderField;
        
        private string groupIdField;
        
        private string lastNameField;
        
        private string mIFirstNameField;
        
        private string mILastNameField;
        
        private string mIMemberNoField;
        
        private string memberNoField;
        
        private string nationalIdField;
        
        private int payerIDField;
        
        private int personCodeField;
        
        private ushort relationshipCodeField;
        
        private bool relationshipCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("dateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateOfBirthSpecified {
            get {
                return this.dateOfBirthFieldSpecified;
            }
            set {
                this.dateOfBirthFieldSpecified = value;
                this.RaisePropertyChanged("dateOfBirthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string divisionId {
            get {
                return this.divisionIdField;
            }
            set {
                this.divisionIdField = value;
                this.RaisePropertyChanged("divisionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime effectiveFrom {
            get {
                return this.effectiveFromField;
            }
            set {
                this.effectiveFromField = value;
                this.RaisePropertyChanged("effectiveFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool effectiveFromSpecified {
            get {
                return this.effectiveFromFieldSpecified;
            }
            set {
                this.effectiveFromFieldSpecified = value;
                this.RaisePropertyChanged("effectiveFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime effectiveTo {
            get {
                return this.effectiveToField;
            }
            set {
                this.effectiveToField = value;
                this.RaisePropertyChanged("effectiveTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool effectiveToSpecified {
            get {
                return this.effectiveToFieldSpecified;
            }
            set {
                this.effectiveToFieldSpecified = value;
                this.RaisePropertyChanged("effectiveToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ushort gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("groupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MIFirstName {
            get {
                return this.mIFirstNameField;
            }
            set {
                this.mIFirstNameField = value;
                this.RaisePropertyChanged("MIFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MILastName {
            get {
                return this.mILastNameField;
            }
            set {
                this.mILastNameField = value;
                this.RaisePropertyChanged("MILastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string MIMemberNo {
            get {
                return this.mIMemberNoField;
            }
            set {
                this.mIMemberNoField = value;
                this.RaisePropertyChanged("MIMemberNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string memberNo {
            get {
                return this.memberNoField;
            }
            set {
                this.memberNoField = value;
                this.RaisePropertyChanged("memberNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string nationalId {
            get {
                return this.nationalIdField;
            }
            set {
                this.nationalIdField = value;
                this.RaisePropertyChanged("nationalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int payerID {
            get {
                return this.payerIDField;
            }
            set {
                this.payerIDField = value;
                this.RaisePropertyChanged("payerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int personCode {
            get {
                return this.personCodeField;
            }
            set {
                this.personCodeField = value;
                this.RaisePropertyChanged("personCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public ushort relationshipCode {
            get {
                return this.relationshipCodeField;
            }
            set {
                this.relationshipCodeField = value;
                this.RaisePropertyChanged("relationshipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool relationshipCodeSpecified {
            get {
                return this.relationshipCodeFieldSpecified;
            }
            set {
                this.relationshipCodeFieldSpecified = value;
                this.RaisePropertyChanged("relationshipCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMemebrBatch", WrapperNamespace="http://memberMgr.ws.bus.dimensions.com/", IsWrapped=true)]
    public partial class updateMemebrBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("membersList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services_All.PbmS_Member.memberRecordDTO[] membersList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string registrationKey;
        
        public updateMemebrBatchRequest() {
        }
        
        public updateMemebrBatchRequest(Services_All.PbmS_Member.memberRecordDTO[] membersList, string registrationKey) {
            this.membersList = membersList;
            this.registrationKey = registrationKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMemebrBatchResponse", WrapperNamespace="http://memberMgr.ws.bus.dimensions.com/", IsWrapped=true)]
    public partial class updateMemebrBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public updateMemebrBatchResponse() {
        }
        
        public updateMemebrBatchResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMemebr", WrapperNamespace="http://memberMgr.ws.bus.dimensions.com/", IsWrapped=true)]
    public partial class updateMemebrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services_All.PbmS_Member.memberRecordDTO member;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int payerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string registrationKey;
        
        public updateMemebrRequest() {
        }
        
        public updateMemebrRequest(Services_All.PbmS_Member.memberRecordDTO member, int payerId, string registrationKey) {
            this.member = member;
            this.payerId = payerId;
            this.registrationKey = registrationKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMemebrResponse", WrapperNamespace="http://memberMgr.ws.bus.dimensions.com/", IsWrapped=true)]
    public partial class updateMemebrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateMemebrResponse() {
        }
        
        public updateMemebrResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/")]
    public partial class memberDetailsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int isValidField;
        
        private bool isValidFieldSpecified;
        
        private string mSGField;
        
        private memberRecordDTO memberField;
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int isValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("isValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isValidSpecified {
            get {
                return this.isValidFieldSpecified;
            }
            set {
                this.isValidFieldSpecified = value;
                this.RaisePropertyChanged("isValidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MSG {
            get {
                return this.mSGField;
            }
            set {
                this.mSGField = value;
                this.RaisePropertyChanged("MSG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public memberRecordDTO member {
            get {
                return this.memberField;
            }
            set {
                this.memberField = value;
                this.RaisePropertyChanged("member");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("valueSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMemberDetails", WrapperNamespace="http://memberMgr.ws.bus.dimensions.com/", IsWrapped=true)]
    public partial class getMemberDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int payerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string memberId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authKey;
        
        public getMemberDetailsRequest() {
        }
        
        public getMemberDetailsRequest(int payerId, string memberId, string authKey) {
            this.payerId = payerId;
            this.memberId = memberId;
            this.authKey = authKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMemberDetailsResponse", WrapperNamespace="http://memberMgr.ws.bus.dimensions.com/", IsWrapped=true)]
    public partial class getMemberDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://memberMgr.ws.bus.dimensions.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services_All.PbmS_Member.memberDetailsResult @return;
        
        public getMemberDetailsResponse() {
        }
        
        public getMemberDetailsResponse(Services_All.PbmS_Member.memberDetailsResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MemberUpdateWSChannel : Services_All.PbmS_Member.MemberUpdateWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberUpdateWSClient : System.ServiceModel.ClientBase<Services_All.PbmS_Member.MemberUpdateWS>, Services_All.PbmS_Member.MemberUpdateWS {
        
        public MemberUpdateWSClient() {
        }
        
        public MemberUpdateWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberUpdateWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberUpdateWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberUpdateWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.PbmS_Member.updateMemberExclusionResponse Services_All.PbmS_Member.MemberUpdateWS.updateMemberExclusion(Services_All.PbmS_Member.updateMemberExclusionRequest request) {
            return base.Channel.updateMemberExclusion(request);
        }
        
        public Services_All.PbmS_Member.feedbackResult updateMemberExclusion(int payerId, Services_All.PbmS_Member.memberExclusion[] memberExclusionsList, string registrationKey) {
            Services_All.PbmS_Member.updateMemberExclusionRequest inValue = new Services_All.PbmS_Member.updateMemberExclusionRequest();
            inValue.payerId = payerId;
            inValue.memberExclusionsList = memberExclusionsList;
            inValue.registrationKey = registrationKey;
            Services_All.PbmS_Member.updateMemberExclusionResponse retVal = ((Services_All.PbmS_Member.MemberUpdateWS)(this)).updateMemberExclusion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.PbmS_Member.updateMemberExclusionResponse> Services_All.PbmS_Member.MemberUpdateWS.updateMemberExclusionAsync(Services_All.PbmS_Member.updateMemberExclusionRequest request) {
            return base.Channel.updateMemberExclusionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.PbmS_Member.updateMemberExclusionResponse> updateMemberExclusionAsync(int payerId, Services_All.PbmS_Member.memberExclusion[] memberExclusionsList, string registrationKey) {
            Services_All.PbmS_Member.updateMemberExclusionRequest inValue = new Services_All.PbmS_Member.updateMemberExclusionRequest();
            inValue.payerId = payerId;
            inValue.memberExclusionsList = memberExclusionsList;
            inValue.registrationKey = registrationKey;
            return ((Services_All.PbmS_Member.MemberUpdateWS)(this)).updateMemberExclusionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.PbmS_Member.updateMemebrBatchResponse Services_All.PbmS_Member.MemberUpdateWS.updateMemebrBatch(Services_All.PbmS_Member.updateMemebrBatchRequest request) {
            return base.Channel.updateMemebrBatch(request);
        }
        
        public string[] updateMemebrBatch(Services_All.PbmS_Member.memberRecordDTO[] membersList, string registrationKey) {
            Services_All.PbmS_Member.updateMemebrBatchRequest inValue = new Services_All.PbmS_Member.updateMemebrBatchRequest();
            inValue.membersList = membersList;
            inValue.registrationKey = registrationKey;
            Services_All.PbmS_Member.updateMemebrBatchResponse retVal = ((Services_All.PbmS_Member.MemberUpdateWS)(this)).updateMemebrBatch(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.PbmS_Member.updateMemebrBatchResponse> Services_All.PbmS_Member.MemberUpdateWS.updateMemebrBatchAsync(Services_All.PbmS_Member.updateMemebrBatchRequest request) {
            return base.Channel.updateMemebrBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.PbmS_Member.updateMemebrBatchResponse> updateMemebrBatchAsync(Services_All.PbmS_Member.memberRecordDTO[] membersList, string registrationKey) {
            Services_All.PbmS_Member.updateMemebrBatchRequest inValue = new Services_All.PbmS_Member.updateMemebrBatchRequest();
            inValue.membersList = membersList;
            inValue.registrationKey = registrationKey;
            return ((Services_All.PbmS_Member.MemberUpdateWS)(this)).updateMemebrBatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.PbmS_Member.updateMemebrResponse Services_All.PbmS_Member.MemberUpdateWS.updateMemebr(Services_All.PbmS_Member.updateMemebrRequest request) {
            return base.Channel.updateMemebr(request);
        }
        
        public bool updateMemebr(Services_All.PbmS_Member.memberRecordDTO member, int payerId, string registrationKey) {
            Services_All.PbmS_Member.updateMemebrRequest inValue = new Services_All.PbmS_Member.updateMemebrRequest();
            inValue.member = member;
            inValue.payerId = payerId;
            inValue.registrationKey = registrationKey;
            Services_All.PbmS_Member.updateMemebrResponse retVal = ((Services_All.PbmS_Member.MemberUpdateWS)(this)).updateMemebr(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.PbmS_Member.updateMemebrResponse> Services_All.PbmS_Member.MemberUpdateWS.updateMemebrAsync(Services_All.PbmS_Member.updateMemebrRequest request) {
            return base.Channel.updateMemebrAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.PbmS_Member.updateMemebrResponse> updateMemebrAsync(Services_All.PbmS_Member.memberRecordDTO member, int payerId, string registrationKey) {
            Services_All.PbmS_Member.updateMemebrRequest inValue = new Services_All.PbmS_Member.updateMemebrRequest();
            inValue.member = member;
            inValue.payerId = payerId;
            inValue.registrationKey = registrationKey;
            return ((Services_All.PbmS_Member.MemberUpdateWS)(this)).updateMemebrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.PbmS_Member.getMemberDetailsResponse Services_All.PbmS_Member.MemberUpdateWS.getMemberDetails(Services_All.PbmS_Member.getMemberDetailsRequest request) {
            return base.Channel.getMemberDetails(request);
        }
        
        public Services_All.PbmS_Member.memberDetailsResult getMemberDetails(int payerId, string memberId, string authKey) {
            Services_All.PbmS_Member.getMemberDetailsRequest inValue = new Services_All.PbmS_Member.getMemberDetailsRequest();
            inValue.payerId = payerId;
            inValue.memberId = memberId;
            inValue.authKey = authKey;
            Services_All.PbmS_Member.getMemberDetailsResponse retVal = ((Services_All.PbmS_Member.MemberUpdateWS)(this)).getMemberDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.PbmS_Member.getMemberDetailsResponse> Services_All.PbmS_Member.MemberUpdateWS.getMemberDetailsAsync(Services_All.PbmS_Member.getMemberDetailsRequest request) {
            return base.Channel.getMemberDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.PbmS_Member.getMemberDetailsResponse> getMemberDetailsAsync(int payerId, string memberId, string authKey) {
            Services_All.PbmS_Member.getMemberDetailsRequest inValue = new Services_All.PbmS_Member.getMemberDetailsRequest();
            inValue.payerId = payerId;
            inValue.memberId = memberId;
            inValue.authKey = authKey;
            return ((Services_All.PbmS_Member.MemberUpdateWS)(this)).getMemberDetailsAsync(inValue);
        }
    }
}
