//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services_All.NahdiVPN {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NahdiVPN.IIntegration")]
    public interface IIntegration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/GetBupaEligibility", ReplyAction="http://tempuri.org/IIntegration/GetBupaEligibilityResponse")]
        Services_All.NahdiVPN.GetBupaEligibilityResponse GetBupaEligibility(Services_All.NahdiVPN.GetBupaEligibilityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/GetBupaEligibility", ReplyAction="http://tempuri.org/IIntegration/GetBupaEligibilityResponse")]
        System.Threading.Tasks.Task<Services_All.NahdiVPN.GetBupaEligibilityResponse> GetBupaEligibilityAsync(Services_All.NahdiVPN.GetBupaEligibilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/GetWaseelEligibility", ReplyAction="http://tempuri.org/IIntegration/GetWaseelEligibilityResponse")]
        Services_All.NahdiVPN.GetWaseelEligibilityResponse GetWaseelEligibility(Services_All.NahdiVPN.GetWaseelEligibilityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/GetWaseelEligibility", ReplyAction="http://tempuri.org/IIntegration/GetWaseelEligibilityResponse")]
        System.Threading.Tasks.Task<Services_All.NahdiVPN.GetWaseelEligibilityResponse> GetWaseelEligibilityAsync(Services_All.NahdiVPN.GetWaseelEligibilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/GetWaseelApprovalSubmission", ReplyAction="http://tempuri.org/IIntegration/GetWaseelApprovalSubmissionResponse")]
        Services_All.NahdiVPN.GetWaseelApprovalSubmissionResponse GetWaseelApprovalSubmission(Services_All.NahdiVPN.GetWaseelApprovalSubmissionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/GetWaseelApprovalSubmission", ReplyAction="http://tempuri.org/IIntegration/GetWaseelApprovalSubmissionResponse")]
        System.Threading.Tasks.Task<Services_All.NahdiVPN.GetWaseelApprovalSubmissionResponse> GetWaseelApprovalSubmissionAsync(Services_All.NahdiVPN.GetWaseelApprovalSubmissionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBupaEligibility", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBupaEligibilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] request;
        
        public GetBupaEligibilityRequest() {
        }
        
        public GetBupaEligibilityRequest(byte[] request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBupaEligibilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBupaEligibilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] GetBupaEligibilityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool resultStatus;
        
        public GetBupaEligibilityResponse() {
        }
        
        public GetBupaEligibilityResponse(byte[] GetBupaEligibilityResult, bool resultStatus) {
            this.GetBupaEligibilityResult = GetBupaEligibilityResult;
            this.resultStatus = resultStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaseelEligibility", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaseelEligibilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] request;
        
        public GetWaseelEligibilityRequest() {
        }
        
        public GetWaseelEligibilityRequest(byte[] request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaseelEligibilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaseelEligibilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] GetWaseelEligibilityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool resultStatus;
        
        public GetWaseelEligibilityResponse() {
        }
        
        public GetWaseelEligibilityResponse(byte[] GetWaseelEligibilityResult, bool resultStatus) {
            this.GetWaseelEligibilityResult = GetWaseelEligibilityResult;
            this.resultStatus = resultStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaseelApprovalSubmission", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaseelApprovalSubmissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] request;
        
        public GetWaseelApprovalSubmissionRequest() {
        }
        
        public GetWaseelApprovalSubmissionRequest(byte[] request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaseelApprovalSubmissionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaseelApprovalSubmissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] GetWaseelApprovalSubmissionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool resultStatus;
        
        public GetWaseelApprovalSubmissionResponse() {
        }
        
        public GetWaseelApprovalSubmissionResponse(byte[] GetWaseelApprovalSubmissionResult, bool resultStatus) {
            this.GetWaseelApprovalSubmissionResult = GetWaseelApprovalSubmissionResult;
            this.resultStatus = resultStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegrationChannel : Services_All.NahdiVPN.IIntegration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationClient : System.ServiceModel.ClientBase<Services_All.NahdiVPN.IIntegration>, Services_All.NahdiVPN.IIntegration {
        
        public IntegrationClient() {
        }
        
        public IntegrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.NahdiVPN.GetBupaEligibilityResponse Services_All.NahdiVPN.IIntegration.GetBupaEligibility(Services_All.NahdiVPN.GetBupaEligibilityRequest request) {
            return base.Channel.GetBupaEligibility(request);
        }
        
        public byte[] GetBupaEligibility(byte[] request, out bool resultStatus) {
            Services_All.NahdiVPN.GetBupaEligibilityRequest inValue = new Services_All.NahdiVPN.GetBupaEligibilityRequest();
            inValue.request = request;
            Services_All.NahdiVPN.GetBupaEligibilityResponse retVal = ((Services_All.NahdiVPN.IIntegration)(this)).GetBupaEligibility(inValue);
            resultStatus = retVal.resultStatus;
            return retVal.GetBupaEligibilityResult;
        }
        
        public System.Threading.Tasks.Task<Services_All.NahdiVPN.GetBupaEligibilityResponse> GetBupaEligibilityAsync(Services_All.NahdiVPN.GetBupaEligibilityRequest request) {
            return base.Channel.GetBupaEligibilityAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.NahdiVPN.GetWaseelEligibilityResponse Services_All.NahdiVPN.IIntegration.GetWaseelEligibility(Services_All.NahdiVPN.GetWaseelEligibilityRequest request) {
            return base.Channel.GetWaseelEligibility(request);
        }
        
        public byte[] GetWaseelEligibility(byte[] request, out bool resultStatus) {
            Services_All.NahdiVPN.GetWaseelEligibilityRequest inValue = new Services_All.NahdiVPN.GetWaseelEligibilityRequest();
            inValue.request = request;
            Services_All.NahdiVPN.GetWaseelEligibilityResponse retVal = ((Services_All.NahdiVPN.IIntegration)(this)).GetWaseelEligibility(inValue);
            resultStatus = retVal.resultStatus;
            return retVal.GetWaseelEligibilityResult;
        }
        
        public System.Threading.Tasks.Task<Services_All.NahdiVPN.GetWaseelEligibilityResponse> GetWaseelEligibilityAsync(Services_All.NahdiVPN.GetWaseelEligibilityRequest request) {
            return base.Channel.GetWaseelEligibilityAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.NahdiVPN.GetWaseelApprovalSubmissionResponse Services_All.NahdiVPN.IIntegration.GetWaseelApprovalSubmission(Services_All.NahdiVPN.GetWaseelApprovalSubmissionRequest request) {
            return base.Channel.GetWaseelApprovalSubmission(request);
        }
        
        public byte[] GetWaseelApprovalSubmission(byte[] request, out bool resultStatus) {
            Services_All.NahdiVPN.GetWaseelApprovalSubmissionRequest inValue = new Services_All.NahdiVPN.GetWaseelApprovalSubmissionRequest();
            inValue.request = request;
            Services_All.NahdiVPN.GetWaseelApprovalSubmissionResponse retVal = ((Services_All.NahdiVPN.IIntegration)(this)).GetWaseelApprovalSubmission(inValue);
            resultStatus = retVal.resultStatus;
            return retVal.GetWaseelApprovalSubmissionResult;
        }
        
        public System.Threading.Tasks.Task<Services_All.NahdiVPN.GetWaseelApprovalSubmissionResponse> GetWaseelApprovalSubmissionAsync(Services_All.NahdiVPN.GetWaseelApprovalSubmissionRequest request) {
            return base.Channel.GetWaseelApprovalSubmissionAsync(request);
        }
    }
}
