//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services_All.Ceed_Dhceg {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", ConfigurationName="Ceed_Dhceg.GatewaySoap")]
    public interface GatewaySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DHCEG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Services_All.Ceed_Dhceg.DHCEGResponse DHCEG(Services_All.Ceed_Dhceg.DHCEGRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DHCEG", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.DHCEGResponse> DHCEGAsync(Services_All.Ceed_Dhceg.DHCEGRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DHCEG_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Services_All.Ceed_Dhceg.DHCEG_UpdateResponse DHCEG_Update(Services_All.Ceed_Dhceg.DHCEG_UpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DHCEG_Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.DHCEG_UpdateResponse> DHCEG_UpdateAsync(Services_All.Ceed_Dhceg.DHCEG_UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DHCEG_Claims", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Services_All.Ceed_Dhceg.DHCEG_ClaimsResponse DHCEG_Claims(Services_All.Ceed_Dhceg.DHCEG_ClaimsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DHCEG_Claims", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.DHCEG_ClaimsResponse> DHCEG_ClaimsAsync(Services_All.Ceed_Dhceg.DHCEG_ClaimsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DrugContraindicationAlerts" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DrugContraindicationAlerts(string ContraRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DrugContraindicationAlerts" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DrugContraindicationAlertsAsync(string ContraRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DrugPrecautionsAlerts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DrugPrecautionsAlerts(string ContraRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DrugPrecautionsAlerts", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DrugPrecautionsAlertsAsync(string ContraRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DrugInteractionAlerts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DrugInteractionAlerts(string InteractionRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/DrugInteractionAlerts", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DrugInteractionAlertsAsync(string InteractionRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/SearchAllergyAlerts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SearchAllergyAlerts(string AllergyRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/SearchAllergyAlerts", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SearchAllergyAlertsAsync(string AllergyRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/Cim10Service", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Cim10Service(string PreRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/Cim10Service", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Cim10ServiceAsync(string PreRequest, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Services_All.Ceed_Dhceg.CreateUserResponse CreateUser(Services_All.Ceed_Dhceg.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.CreateUserResponse> CreateUserAsync(Services_All.Ceed_Dhceg.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/UpdateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Services_All.Ceed_Dhceg.UpdateUserResponse UpdateUser(Services_All.Ceed_Dhceg.UpdateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.UpdateUserResponse> UpdateUserAsync(Services_All.Ceed_Dhceg.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/RegisterService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegisterService(string mac, string ip, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/RegisterService", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RegisterServiceAsync(string mac, string ip, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/GetMyIpService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMyIpService(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/GetMyIpService", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMyIpServiceAsync(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/GetCurVersionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCurVersionService(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/GetCurVersionService", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCurVersionServiceAsync(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/GetDHCEGValueService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Services_All.Ceed_Dhceg.GetDHCEGValueServiceResponse GetDHCEGValueService(Services_All.Ceed_Dhceg.GetDHCEGValueServiceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes/GetDHCEGValueService", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.GetDHCEGValueServiceResponse> GetDHCEGValueServiceAsync(Services_All.Ceed_Dhceg.GetDHCEGValueServiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseClaimEdit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string refNumField;
        
        private string dateTimeField;
        
        private string engineVersionField;
        
        private responseClaimEditEdit[] editField;
        
        private responseClaimEditActivityEdit[] activityEditField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RefNum {
            get {
                return this.refNumField;
            }
            set {
                this.refNumField = value;
                this.RaisePropertyChanged("RefNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("DateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EngineVersion {
            get {
                return this.engineVersionField;
            }
            set {
                this.engineVersionField = value;
                this.RaisePropertyChanged("EngineVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Edit", Order=4)]
        public responseClaimEditEdit[] Edit {
            get {
                return this.editField;
            }
            set {
                this.editField = value;
                this.RaisePropertyChanged("Edit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActivityEdit", Order=5)]
        public responseClaimEditActivityEdit[] ActivityEdit {
            get {
                return this.activityEditField;
            }
            set {
                this.activityEditField = value;
                this.RaisePropertyChanged("ActivityEdit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseClaimEditEdit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string typeField;
        
        private string subTypeField;
        
        private string codeField;
        
        private ClaimEditRank rankField;
        
        private string resultCodeField;
        
        private string resultField;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
                this.RaisePropertyChanged("SubType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ClaimEditRank Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("Rank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum ClaimEditRank {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        NA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseClaimEditActivityEdit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string codeField;
        
        private string[] editIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EditId", Order=2)]
        public string[] EditId {
            get {
                return this.editIdField;
            }
            set {
                this.editIdField = value;
                this.RaisePropertyChanged("EditId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DHCEG", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class DHCEGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public string service;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=1)]
        public object request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=3)]
        public string password;
        
        public DHCEGRequest() {
        }
        
        public DHCEGRequest(string service, object request, string user, string password) {
            this.service = service;
            this.request = request;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DHCEGResponse", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class DHCEGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public int DHCEGResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClaimEdit", IsNullable=false)]
        public Services_All.Ceed_Dhceg.responseClaimEdit[] response;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=2)]
        public string infoMessage;
        
        public DHCEGResponse() {
        }
        
        public DHCEGResponse(int DHCEGResult, Services_All.Ceed_Dhceg.responseClaimEdit[] response, string infoMessage) {
            this.DHCEGResult = DHCEGResult;
            this.response = response;
            this.infoMessage = infoMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DHCEG_Update", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class DHCEG_UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public string service;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=1)]
        public object request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=4)]
        public int logId;
        
        public DHCEG_UpdateRequest() {
        }
        
        public DHCEG_UpdateRequest(string service, object request, string user, string password, int logId) {
            this.service = service;
            this.request = request;
            this.user = user;
            this.password = password;
            this.logId = logId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DHCEG_UpdateResponse", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class DHCEG_UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public int DHCEG_UpdateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClaimEdit", IsNullable=false)]
        public Services_All.Ceed_Dhceg.responseClaimEdit[] response;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=2)]
        public string infoMessage;
        
        public DHCEG_UpdateResponse() {
        }
        
        public DHCEG_UpdateResponse(int DHCEG_UpdateResult, Services_All.Ceed_Dhceg.responseClaimEdit[] response, string infoMessage) {
            this.DHCEG_UpdateResult = DHCEG_UpdateResult;
            this.response = response;
            this.infoMessage = infoMessage;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestClaim : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private requestClaimPerson personField;
        
        private requestClaimEncounter encounterField;
        
        private requestClaimDiagnosis[] diagnosisField;
        
        private requestClaimActivity[] activityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public requestClaimPerson Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
                this.RaisePropertyChanged("Person");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public requestClaimEncounter Encounter {
            get {
                return this.encounterField;
            }
            set {
                this.encounterField = value;
                this.RaisePropertyChanged("Encounter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Diagnosis", Order=3)]
        public requestClaimDiagnosis[] Diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
                this.RaisePropertyChanged("Diagnosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Activity", Order=4)]
        public requestClaimActivity[] Activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
                this.RaisePropertyChanged("Activity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestClaimPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string birthDateField;
        
        private Gender genderField;
        
        private bool genderFieldSpecified;
        
        private string weightField;
        
        private BreastFeeding breastFeedingField;
        
        private bool breastFeedingFieldSpecified;
        
        private string weeksOfAmenorrhoeaField;
        
        private string creatinClearanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
                this.RaisePropertyChanged("GenderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public BreastFeeding BreastFeeding {
            get {
                return this.breastFeedingField;
            }
            set {
                this.breastFeedingField = value;
                this.RaisePropertyChanged("BreastFeeding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BreastFeedingSpecified {
            get {
                return this.breastFeedingFieldSpecified;
            }
            set {
                this.breastFeedingFieldSpecified = value;
                this.RaisePropertyChanged("BreastFeedingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string WeeksOfAmenorrhoea {
            get {
                return this.weeksOfAmenorrhoeaField;
            }
            set {
                this.weeksOfAmenorrhoeaField = value;
                this.RaisePropertyChanged("WeeksOfAmenorrhoea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string CreatinClearance {
            get {
                return this.creatinClearanceField;
            }
            set {
                this.creatinClearanceField = value;
                this.RaisePropertyChanged("CreatinClearance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum Gender {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        U,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum BreastFeeding {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestClaimEncounter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EncounterType typeField;
        
        private string startField;
        
        private string endField;
        
        private EncounterStartType startTypeField;
        
        private bool startTypeFieldSpecified;
        
        private EncounterEndType endTypeField;
        
        private bool endTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EncounterType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public EncounterStartType StartType {
            get {
                return this.startTypeField;
            }
            set {
                this.startTypeField = value;
                this.RaisePropertyChanged("StartType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTypeSpecified {
            get {
                return this.startTypeFieldSpecified;
            }
            set {
                this.startTypeFieldSpecified = value;
                this.RaisePropertyChanged("StartTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public EncounterEndType EndType {
            get {
                return this.endTypeField;
            }
            set {
                this.endTypeField = value;
                this.RaisePropertyChanged("EndType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndTypeSpecified {
            get {
                return this.endTypeFieldSpecified;
            }
            set {
                this.endTypeFieldSpecified = value;
                this.RaisePropertyChanged("EndTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum EncounterType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum EncounterStartType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum EncounterEndType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestClaimDiagnosis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DiagnosisCodeTerm codeTermField;
        
        private DiagnosisType typeField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DiagnosisCodeTerm CodeTerm {
            get {
                return this.codeTermField;
            }
            set {
                this.codeTermField = value;
                this.RaisePropertyChanged("CodeTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DiagnosisType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum DiagnosisCodeTerm {
        
        /// <remarks/>
        ICD10,
        
        /// <remarks/>
        ICD9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum DiagnosisType {
        
        /// <remarks/>
        Principal,
        
        /// <remarks/>
        Secondary,
        
        /// <remarks/>
        Admitting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestClaimActivity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private ActivityCodeTerm codeTermField;
        
        private string startField;
        
        private string codeField;
        
        private float quantityField;
        
        private string clinicianField;
        
        private requestClaimActivityObservation[] observationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ActivityCodeTerm CodeTerm {
            get {
                return this.codeTermField;
            }
            set {
                this.codeTermField = value;
                this.RaisePropertyChanged("CodeTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Clinician {
            get {
                return this.clinicianField;
            }
            set {
                this.clinicianField = value;
                this.RaisePropertyChanged("Clinician");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Observation", Order=6)]
        public requestClaimActivityObservation[] Observation {
            get {
                return this.observationField;
            }
            set {
                this.observationField = value;
                this.RaisePropertyChanged("Observation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum ActivityCodeTerm {
        
        /// <remarks/>
        CPT4v2012,
        
        /// <remarks/>
        CPT4v2011,
        
        /// <remarks/>
        DSL,
        
        /// <remarks/>
        DDC,
        
        /// <remarks/>
        HCPCS,
        
        /// <remarks/>
        ADA,
        
        /// <remarks/>
        CDT,
        
        /// <remarks/>
        HAAD,
        
        /// <remarks/>
        MEDD,
        
        /// <remarks/>
        ASL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestClaimActivityObservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private ObservationType typeField;
        
        private string codeField;
        
        private string valueField;
        
        private string valueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ObservationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
                this.RaisePropertyChanged("ValueType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes")]
    public enum ObservationType {
        
        /// <remarks/>
        LOINC,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        File,
        
        /// <remarks/>
        UniversalDental,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Universal Dental")]
        UniversalDental1,
        
        /// <remarks/>
        Financial,
        
        /// <remarks/>
        Grouping,
        
        /// <remarks/>
        Modifier,
        
        /// <remarks/>
        ERX,
        
        /// <remarks/>
        Result,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DHCEG_Claims", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class DHCEG_ClaimsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public string service;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Claim", IsNullable=false)]
        public Services_All.Ceed_Dhceg.requestClaim[] request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=3)]
        public string password;
        
        public DHCEG_ClaimsRequest() {
        }
        
        public DHCEG_ClaimsRequest(string service, Services_All.Ceed_Dhceg.requestClaim[] request, string user, string password) {
            this.service = service;
            this.request = request;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DHCEG_ClaimsResponse", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class DHCEG_ClaimsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public int DHCEG_ClaimsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClaimEdit", IsNullable=false)]
        public Services_All.Ceed_Dhceg.responseClaimEdit[] response;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=2)]
        public string infoMessage;
        
        public DHCEG_ClaimsResponse() {
        }
        
        public DHCEG_ClaimsResponse(int DHCEG_ClaimsResult, Services_All.Ceed_Dhceg.responseClaimEdit[] response, string infoMessage) {
            this.DHCEG_ClaimsResult = DHCEG_ClaimsResult;
            this.response = response;
            this.infoMessage = infoMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUser", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public string appUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=1)]
        public string appPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=2)]
        public string newUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=3)]
        public string newUserPassword;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(string appUser, string appPassword, string newUser, string newUserPassword) {
            this.appUser = appUser;
            this.appPassword = appPassword;
            this.newUser = newUser;
            this.newUserPassword = newUserPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserResponse", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public bool CreateUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=1)]
        public string message;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(bool CreateUserResult, string message) {
            this.CreateUserResult = CreateUserResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUser", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public string appUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=1)]
        public string appPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=2)]
        public string updateUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=3)]
        public string newPassword;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(string appUser, string appPassword, string updateUser, string newPassword) {
            this.appUser = appUser;
            this.appPassword = appPassword;
            this.updateUser = updateUser;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserResponse", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public bool UpdateUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=1)]
        public string message;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(bool UpdateUserResult, string message) {
            this.UpdateUserResult = UpdateUserResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDHCEGValueService", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class GetDHCEGValueServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=2)]
        public string value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=3)]
        public string type;
        
        public GetDHCEGValueServiceRequest() {
        }
        
        public GetDHCEGValueServiceRequest(string user, string password, string value, string type) {
            this.user = user;
            this.password = password;
            this.value = value;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDHCEGValueServiceResponse", WrapperNamespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", IsWrapped=true)]
    public partial class GetDHCEGValueServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=0)]
        public int GetDHCEGValueServiceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.Dimensions-healthcare.net/DHCEG/CommonTypes", Order=1)]
        public string message;
        
        public GetDHCEGValueServiceResponse() {
        }
        
        public GetDHCEGValueServiceResponse(int GetDHCEGValueServiceResult, string message) {
            this.GetDHCEGValueServiceResult = GetDHCEGValueServiceResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GatewaySoapChannel : Services_All.Ceed_Dhceg.GatewaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewaySoapClient : System.ServiceModel.ClientBase<Services_All.Ceed_Dhceg.GatewaySoap>, Services_All.Ceed_Dhceg.GatewaySoap {
        
        public GatewaySoapClient() {
        }
        
        public GatewaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Ceed_Dhceg.DHCEGResponse Services_All.Ceed_Dhceg.GatewaySoap.DHCEG(Services_All.Ceed_Dhceg.DHCEGRequest request) {
            return base.Channel.DHCEG(request);
        }
        
        public int DHCEG(string service, object request, string user, string password, out Services_All.Ceed_Dhceg.responseClaimEdit[] response, out string infoMessage) {
            Services_All.Ceed_Dhceg.DHCEGRequest inValue = new Services_All.Ceed_Dhceg.DHCEGRequest();
            inValue.service = service;
            inValue.request = request;
            inValue.user = user;
            inValue.password = password;
            Services_All.Ceed_Dhceg.DHCEGResponse retVal = ((Services_All.Ceed_Dhceg.GatewaySoap)(this)).DHCEG(inValue);
            response = retVal.response;
            infoMessage = retVal.infoMessage;
            return retVal.DHCEGResult;
        }
        
        public System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.DHCEGResponse> DHCEGAsync(Services_All.Ceed_Dhceg.DHCEGRequest request) {
            return base.Channel.DHCEGAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Ceed_Dhceg.DHCEG_UpdateResponse Services_All.Ceed_Dhceg.GatewaySoap.DHCEG_Update(Services_All.Ceed_Dhceg.DHCEG_UpdateRequest request) {
            return base.Channel.DHCEG_Update(request);
        }
        
        public int DHCEG_Update(string service, object request, string user, string password, int logId, out Services_All.Ceed_Dhceg.responseClaimEdit[] response, out string infoMessage) {
            Services_All.Ceed_Dhceg.DHCEG_UpdateRequest inValue = new Services_All.Ceed_Dhceg.DHCEG_UpdateRequest();
            inValue.service = service;
            inValue.request = request;
            inValue.user = user;
            inValue.password = password;
            inValue.logId = logId;
            Services_All.Ceed_Dhceg.DHCEG_UpdateResponse retVal = ((Services_All.Ceed_Dhceg.GatewaySoap)(this)).DHCEG_Update(inValue);
            response = retVal.response;
            infoMessage = retVal.infoMessage;
            return retVal.DHCEG_UpdateResult;
        }
        
        public System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.DHCEG_UpdateResponse> DHCEG_UpdateAsync(Services_All.Ceed_Dhceg.DHCEG_UpdateRequest request) {
            return base.Channel.DHCEG_UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Ceed_Dhceg.DHCEG_ClaimsResponse Services_All.Ceed_Dhceg.GatewaySoap.DHCEG_Claims(Services_All.Ceed_Dhceg.DHCEG_ClaimsRequest request) {
            return base.Channel.DHCEG_Claims(request);
        }
        
        public int DHCEG_Claims(string service, Services_All.Ceed_Dhceg.requestClaim[] request, string user, string password, out Services_All.Ceed_Dhceg.responseClaimEdit[] response, out string infoMessage) {
            Services_All.Ceed_Dhceg.DHCEG_ClaimsRequest inValue = new Services_All.Ceed_Dhceg.DHCEG_ClaimsRequest();
            inValue.service = service;
            inValue.request = request;
            inValue.user = user;
            inValue.password = password;
            Services_All.Ceed_Dhceg.DHCEG_ClaimsResponse retVal = ((Services_All.Ceed_Dhceg.GatewaySoap)(this)).DHCEG_Claims(inValue);
            response = retVal.response;
            infoMessage = retVal.infoMessage;
            return retVal.DHCEG_ClaimsResult;
        }
        
        public System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.DHCEG_ClaimsResponse> DHCEG_ClaimsAsync(Services_All.Ceed_Dhceg.DHCEG_ClaimsRequest request) {
            return base.Channel.DHCEG_ClaimsAsync(request);
        }
        
        public string DrugContraindicationAlerts(string ContraRequest, string user, string password) {
            return base.Channel.DrugContraindicationAlerts(ContraRequest, user, password);
        }
        
        public System.Threading.Tasks.Task<string> DrugContraindicationAlertsAsync(string ContraRequest, string user, string password) {
            return base.Channel.DrugContraindicationAlertsAsync(ContraRequest, user, password);
        }
        
        public string DrugPrecautionsAlerts(string ContraRequest, string user, string password) {
            return base.Channel.DrugPrecautionsAlerts(ContraRequest, user, password);
        }
        
        public System.Threading.Tasks.Task<string> DrugPrecautionsAlertsAsync(string ContraRequest, string user, string password) {
            return base.Channel.DrugPrecautionsAlertsAsync(ContraRequest, user, password);
        }
        
        public string DrugInteractionAlerts(string InteractionRequest, string user, string password) {
            return base.Channel.DrugInteractionAlerts(InteractionRequest, user, password);
        }
        
        public System.Threading.Tasks.Task<string> DrugInteractionAlertsAsync(string InteractionRequest, string user, string password) {
            return base.Channel.DrugInteractionAlertsAsync(InteractionRequest, user, password);
        }
        
        public string SearchAllergyAlerts(string AllergyRequest, string user, string password) {
            return base.Channel.SearchAllergyAlerts(AllergyRequest, user, password);
        }
        
        public System.Threading.Tasks.Task<string> SearchAllergyAlertsAsync(string AllergyRequest, string user, string password) {
            return base.Channel.SearchAllergyAlertsAsync(AllergyRequest, user, password);
        }
        
        public string Cim10Service(string PreRequest, string user, string password) {
            return base.Channel.Cim10Service(PreRequest, user, password);
        }
        
        public System.Threading.Tasks.Task<string> Cim10ServiceAsync(string PreRequest, string user, string password) {
            return base.Channel.Cim10ServiceAsync(PreRequest, user, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Ceed_Dhceg.CreateUserResponse Services_All.Ceed_Dhceg.GatewaySoap.CreateUser(Services_All.Ceed_Dhceg.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public bool CreateUser(string appUser, string appPassword, string newUser, string newUserPassword, out string message) {
            Services_All.Ceed_Dhceg.CreateUserRequest inValue = new Services_All.Ceed_Dhceg.CreateUserRequest();
            inValue.appUser = appUser;
            inValue.appPassword = appPassword;
            inValue.newUser = newUser;
            inValue.newUserPassword = newUserPassword;
            Services_All.Ceed_Dhceg.CreateUserResponse retVal = ((Services_All.Ceed_Dhceg.GatewaySoap)(this)).CreateUser(inValue);
            message = retVal.message;
            return retVal.CreateUserResult;
        }
        
        public System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.CreateUserResponse> CreateUserAsync(Services_All.Ceed_Dhceg.CreateUserRequest request) {
            return base.Channel.CreateUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Ceed_Dhceg.UpdateUserResponse Services_All.Ceed_Dhceg.GatewaySoap.UpdateUser(Services_All.Ceed_Dhceg.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public bool UpdateUser(string appUser, string appPassword, string updateUser1, string newPassword, out string message) {
            Services_All.Ceed_Dhceg.UpdateUserRequest inValue = new Services_All.Ceed_Dhceg.UpdateUserRequest();
            inValue.appUser = appUser;
            inValue.appPassword = appPassword;
            inValue.updateUser = updateUser1;
            inValue.newPassword = newPassword;
            Services_All.Ceed_Dhceg.UpdateUserResponse retVal = ((Services_All.Ceed_Dhceg.GatewaySoap)(this)).UpdateUser(inValue);
            message = retVal.message;
            return retVal.UpdateUserResult;
        }
        
        public System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.UpdateUserResponse> UpdateUserAsync(Services_All.Ceed_Dhceg.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public string RegisterService(string mac, string ip, string user, string password) {
            return base.Channel.RegisterService(mac, ip, user, password);
        }
        
        public System.Threading.Tasks.Task<string> RegisterServiceAsync(string mac, string ip, string user, string password) {
            return base.Channel.RegisterServiceAsync(mac, ip, user, password);
        }
        
        public string GetMyIpService(string user, string password) {
            return base.Channel.GetMyIpService(user, password);
        }
        
        public System.Threading.Tasks.Task<string> GetMyIpServiceAsync(string user, string password) {
            return base.Channel.GetMyIpServiceAsync(user, password);
        }
        
        public string GetCurVersionService(string user, string password) {
            return base.Channel.GetCurVersionService(user, password);
        }
        
        public System.Threading.Tasks.Task<string> GetCurVersionServiceAsync(string user, string password) {
            return base.Channel.GetCurVersionServiceAsync(user, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Ceed_Dhceg.GetDHCEGValueServiceResponse Services_All.Ceed_Dhceg.GatewaySoap.GetDHCEGValueService(Services_All.Ceed_Dhceg.GetDHCEGValueServiceRequest request) {
            return base.Channel.GetDHCEGValueService(request);
        }
        
        public int GetDHCEGValueService(string user, string password, string value, string type, out string message) {
            Services_All.Ceed_Dhceg.GetDHCEGValueServiceRequest inValue = new Services_All.Ceed_Dhceg.GetDHCEGValueServiceRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.value = value;
            inValue.type = type;
            Services_All.Ceed_Dhceg.GetDHCEGValueServiceResponse retVal = ((Services_All.Ceed_Dhceg.GatewaySoap)(this)).GetDHCEGValueService(inValue);
            message = retVal.message;
            return retVal.GetDHCEGValueServiceResult;
        }
        
        public System.Threading.Tasks.Task<Services_All.Ceed_Dhceg.GetDHCEGValueServiceResponse> GetDHCEGValueServiceAsync(Services_All.Ceed_Dhceg.GetDHCEGValueServiceRequest request) {
            return base.Channel.GetDHCEGValueServiceAsync(request);
        }
    }
}
