//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services_All.Jordan_LAB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.eClaimLink.ae/", ConfigurationName="Jordan_LAB.LabValidateTransactionSoap")]
    public interface LabValidateTransactionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/UploadlabRequest", ReplyAction="*")]
        Services_All.Jordan_LAB.UploadlabRequestResponse UploadlabRequest(Services_All.Jordan_LAB.UploadlabRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/UploadlabRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.UploadlabRequestResponse> UploadlabRequestAsync(Services_All.Jordan_LAB.UploadlabRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/UploadLabAuthorization", ReplyAction="*")]
        Services_All.Jordan_LAB.UploadLabAuthorizationResponse UploadLabAuthorization(Services_All.Jordan_LAB.UploadLabAuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/UploadLabAuthorization", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.UploadLabAuthorizationResponse> UploadLabAuthorizationAsync(Services_All.Jordan_LAB.UploadLabAuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/DownloadTransactionFile", ReplyAction="*")]
        Services_All.Jordan_LAB.DownloadTransactionFileResponse DownloadTransactionFile(Services_All.Jordan_LAB.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/DownloadTransactionFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.DownloadTransactionFileResponse> DownloadTransactionFileAsync(Services_All.Jordan_LAB.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewTransactions", ReplyAction="*")]
        Services_All.Jordan_LAB.GetNewTransactionsResponse GetNewTransactions(Services_All.Jordan_LAB.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.GetNewTransactionsResponse> GetNewTransactionsAsync(Services_All.Jordan_LAB.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SearchTransactions", ReplyAction="*")]
        Services_All.Jordan_LAB.SearchTransactionsResponse SearchTransactions(Services_All.Jordan_LAB.SearchTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SearchTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.SearchTransactionsResponse> SearchTransactionsAsync(Services_All.Jordan_LAB.SearchTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SetTransactionDownloaded", ReplyAction="*")]
        Services_All.Jordan_LAB.SetTransactionDownloadedResponse SetTransactionDownloaded(Services_All.Jordan_LAB.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SetTransactionDownloaded", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(Services_All.Jordan_LAB.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetLabTransaction", ReplyAction="*")]
        Services_All.Jordan_LAB.GetLabTransactionResponse GetLabTransaction(Services_All.Jordan_LAB.GetLabTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetLabTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.GetLabTransactionResponse> GetLabTransactionAsync(Services_All.Jordan_LAB.GetLabTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetLabListTransactions", ReplyAction="*")]
        Services_All.Jordan_LAB.GetLabListTransactionsResponse GetLabListTransactions(Services_All.Jordan_LAB.GetLabListTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetLabListTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.GetLabListTransactionsResponse> GetLabListTransactionsAsync(Services_All.Jordan_LAB.GetLabListTransactionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadlabRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadlabRequest", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.UploadlabRequestRequestBody Body;
        
        public UploadlabRequestRequest() {
        }
        
        public UploadlabRequestRequest(Services_All.Jordan_LAB.UploadlabRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class UploadlabRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string facilityLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string facilityPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string clinicianLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string clinicianPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] fileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fileName;
        
        public UploadlabRequestRequestBody() {
        }
        
        public UploadlabRequestRequestBody(string facilityLogin, string facilityPwd, string clinicianLogin, string clinicianPwd, byte[] fileContent, string fileName) {
            this.facilityLogin = facilityLogin;
            this.facilityPwd = facilityPwd;
            this.clinicianLogin = clinicianLogin;
            this.clinicianPwd = clinicianPwd;
            this.fileContent = fileContent;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadlabRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadlabRequestResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.UploadlabRequestResponseBody Body;
        
        public UploadlabRequestResponse() {
        }
        
        public UploadlabRequestResponse(Services_All.Jordan_LAB.UploadlabRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class UploadlabRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadlabRequestResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int LabReferenceNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] errorReport;
        
        public UploadlabRequestResponseBody() {
        }
        
        public UploadlabRequestResponseBody(int UploadlabRequestResult, int LabReferenceNo, string errorMessage, byte[] errorReport) {
            this.UploadlabRequestResult = UploadlabRequestResult;
            this.LabReferenceNo = LabReferenceNo;
            this.errorMessage = errorMessage;
            this.errorReport = errorReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadLabAuthorizationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadLabAuthorization", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.UploadLabAuthorizationRequestBody Body;
        
        public UploadLabAuthorizationRequest() {
        }
        
        public UploadLabAuthorizationRequest(Services_All.Jordan_LAB.UploadLabAuthorizationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class UploadLabAuthorizationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PayerLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PayerPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] fileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fileName;
        
        public UploadLabAuthorizationRequestBody() {
        }
        
        public UploadLabAuthorizationRequestBody(string PayerLogin, string PayerPwd, byte[] fileContent, string fileName) {
            this.PayerLogin = PayerLogin;
            this.PayerPwd = PayerPwd;
            this.fileContent = fileContent;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadLabAuthorizationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadLabAuthorizationResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.UploadLabAuthorizationResponseBody Body;
        
        public UploadLabAuthorizationResponse() {
        }
        
        public UploadLabAuthorizationResponse(Services_All.Jordan_LAB.UploadLabAuthorizationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class UploadLabAuthorizationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadLabAuthorizationResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] errorReport;
        
        public UploadLabAuthorizationResponseBody() {
        }
        
        public UploadLabAuthorizationResponseBody(int UploadLabAuthorizationResult, string errorMessage, byte[] errorReport) {
            this.UploadLabAuthorizationResult = UploadLabAuthorizationResult;
            this.errorMessage = errorMessage;
            this.errorReport = errorReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFile", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.DownloadTransactionFileRequestBody Body;
        
        public DownloadTransactionFileRequest() {
        }
        
        public DownloadTransactionFileRequest(Services_All.Jordan_LAB.DownloadTransactionFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class DownloadTransactionFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileId;
        
        public DownloadTransactionFileRequestBody() {
        }
        
        public DownloadTransactionFileRequestBody(string login, string pwd, string fileId) {
            this.login = login;
            this.pwd = pwd;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFileResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.DownloadTransactionFileResponseBody Body;
        
        public DownloadTransactionFileResponse() {
        }
        
        public DownloadTransactionFileResponse(Services_All.Jordan_LAB.DownloadTransactionFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class DownloadTransactionFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DownloadTransactionFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] file;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string errorMessage;
        
        public DownloadTransactionFileResponseBody() {
        }
        
        public DownloadTransactionFileResponseBody(int DownloadTransactionFileResult, string fileName, byte[] file, string errorMessage) {
            this.DownloadTransactionFileResult = DownloadTransactionFileResult;
            this.fileName = fileName;
            this.file = file;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.GetNewTransactionsRequestBody Body;
        
        public GetNewTransactionsRequest() {
        }
        
        public GetNewTransactionsRequest(Services_All.Jordan_LAB.GetNewTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetNewTransactionsRequestBody() {
        }
        
        public GetNewTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.GetNewTransactionsResponseBody Body;
        
        public GetNewTransactionsResponse() {
        }
        
        public GetNewTransactionsResponse(Services_All.Jordan_LAB.GetNewTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNewTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetNewTransactionsResponseBody() {
        }
        
        public GetNewTransactionsResponseBody(int GetNewTransactionsResult, string xmlTransactions, string errorMessage) {
            this.GetNewTransactionsResult = GetNewTransactionsResult;
            this.xmlTransactions = xmlTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.SearchTransactionsRequestBody Body;
        
        public SearchTransactionsRequest() {
        }
        
        public SearchTransactionsRequest(Services_All.Jordan_LAB.SearchTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SearchTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int direction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string callerLicense;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clinicianLicense;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string memberID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> LabReferenceNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int transactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string transactionFromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string transactionToDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int minRecordCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int maxRecordCount;
        
        public SearchTransactionsRequestBody() {
        }
        
        public SearchTransactionsRequestBody(string login, string pwd, int direction, string callerLicense, string clinicianLicense, string memberID, System.Nullable<int> LabReferenceNo, int transactionStatus, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            this.login = login;
            this.pwd = pwd;
            this.direction = direction;
            this.callerLicense = callerLicense;
            this.clinicianLicense = clinicianLicense;
            this.memberID = memberID;
            this.LabReferenceNo = LabReferenceNo;
            this.transactionStatus = transactionStatus;
            this.transactionFromDate = transactionFromDate;
            this.transactionToDate = transactionToDate;
            this.minRecordCount = minRecordCount;
            this.maxRecordCount = maxRecordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.SearchTransactionsResponseBody Body;
        
        public SearchTransactionsResponse() {
        }
        
        public SearchTransactionsResponse(Services_All.Jordan_LAB.SearchTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SearchTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SearchTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string foundTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public SearchTransactionsResponseBody() {
        }
        
        public SearchTransactionsResponseBody(int SearchTransactionsResult, string foundTransactions, string errorMessage) {
            this.SearchTransactionsResult = SearchTransactionsResult;
            this.foundTransactions = foundTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloaded", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.SetTransactionDownloadedRequestBody Body;
        
        public SetTransactionDownloadedRequest() {
        }
        
        public SetTransactionDownloadedRequest(Services_All.Jordan_LAB.SetTransactionDownloadedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SetTransactionDownloadedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileID;
        
        public SetTransactionDownloadedRequestBody() {
        }
        
        public SetTransactionDownloadedRequestBody(string login, string pwd, string fileID) {
            this.login = login;
            this.pwd = pwd;
            this.fileID = fileID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloadedResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.SetTransactionDownloadedResponseBody Body;
        
        public SetTransactionDownloadedResponse() {
        }
        
        public SetTransactionDownloadedResponse(Services_All.Jordan_LAB.SetTransactionDownloadedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SetTransactionDownloadedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SetTransactionDownloadedResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public SetTransactionDownloadedResponseBody() {
        }
        
        public SetTransactionDownloadedResponseBody(int SetTransactionDownloadedResult, string errorMessage) {
            this.SetTransactionDownloadedResult = SetTransactionDownloadedResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLabTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLabTransaction", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.GetLabTransactionRequestBody Body;
        
        public GetLabTransactionRequest() {
        }
        
        public GetLabTransactionRequest(Services_All.Jordan_LAB.GetLabTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetLabTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string memberId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nationalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int LabReferenceNo;
        
        public GetLabTransactionRequestBody() {
        }
        
        public GetLabTransactionRequestBody(string login, string pwd, string memberId, string nationalId, int LabReferenceNo) {
            this.login = login;
            this.pwd = pwd;
            this.memberId = memberId;
            this.nationalId = nationalId;
            this.LabReferenceNo = LabReferenceNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLabTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLabTransactionResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.GetLabTransactionResponseBody Body;
        
        public GetLabTransactionResponse() {
        }
        
        public GetLabTransactionResponse(Services_All.Jordan_LAB.GetLabTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetLabTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetLabTransactionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetLabTransactionResponseBody() {
        }
        
        public GetLabTransactionResponseBody(int GetLabTransactionResult, string xmlTransactions, string errorMessage) {
            this.GetLabTransactionResult = GetLabTransactionResult;
            this.xmlTransactions = xmlTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLabListTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLabListTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.GetLabListTransactionsRequestBody Body;
        
        public GetLabListTransactionsRequest() {
        }
        
        public GetLabListTransactionsRequest(Services_All.Jordan_LAB.GetLabListTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetLabListTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string memberId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nationalId;
        
        public GetLabListTransactionsRequestBody() {
        }
        
        public GetLabListTransactionsRequestBody(string login, string pwd, string memberId, string nationalId) {
            this.login = login;
            this.pwd = pwd;
            this.memberId = memberId;
            this.nationalId = nationalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLabListTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLabListTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public Services_All.Jordan_LAB.GetLabListTransactionsResponseBody Body;
        
        public GetLabListTransactionsResponse() {
        }
        
        public GetLabListTransactionsResponse(Services_All.Jordan_LAB.GetLabListTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetLabListTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetLabListTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetLabListTransactionsResponseBody() {
        }
        
        public GetLabListTransactionsResponseBody(int GetLabListTransactionsResult, string xmlTransactions, string errorMessage) {
            this.GetLabListTransactionsResult = GetLabListTransactionsResult;
            this.xmlTransactions = xmlTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LabValidateTransactionSoapChannel : Services_All.Jordan_LAB.LabValidateTransactionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LabValidateTransactionSoapClient : System.ServiceModel.ClientBase<Services_All.Jordan_LAB.LabValidateTransactionSoap>, Services_All.Jordan_LAB.LabValidateTransactionSoap {
        
        public LabValidateTransactionSoapClient() {
        }
        
        public LabValidateTransactionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabValidateTransactionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabValidateTransactionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabValidateTransactionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Jordan_LAB.UploadlabRequestResponse Services_All.Jordan_LAB.LabValidateTransactionSoap.UploadlabRequest(Services_All.Jordan_LAB.UploadlabRequestRequest request) {
            return base.Channel.UploadlabRequest(request);
        }
        
        public int UploadlabRequest(string facilityLogin, string facilityPwd, string clinicianLogin, string clinicianPwd, byte[] fileContent, string fileName, out int LabReferenceNo, out string errorMessage, out byte[] errorReport) {
            Services_All.Jordan_LAB.UploadlabRequestRequest inValue = new Services_All.Jordan_LAB.UploadlabRequestRequest();
            inValue.Body = new Services_All.Jordan_LAB.UploadlabRequestRequestBody();
            inValue.Body.facilityLogin = facilityLogin;
            inValue.Body.facilityPwd = facilityPwd;
            inValue.Body.clinicianLogin = clinicianLogin;
            inValue.Body.clinicianPwd = clinicianPwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            Services_All.Jordan_LAB.UploadlabRequestResponse retVal = ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).UploadlabRequest(inValue);
            LabReferenceNo = retVal.Body.LabReferenceNo;
            errorMessage = retVal.Body.errorMessage;
            errorReport = retVal.Body.errorReport;
            return retVal.Body.UploadlabRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.UploadlabRequestResponse> Services_All.Jordan_LAB.LabValidateTransactionSoap.UploadlabRequestAsync(Services_All.Jordan_LAB.UploadlabRequestRequest request) {
            return base.Channel.UploadlabRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.Jordan_LAB.UploadlabRequestResponse> UploadlabRequestAsync(string facilityLogin, string facilityPwd, string clinicianLogin, string clinicianPwd, byte[] fileContent, string fileName) {
            Services_All.Jordan_LAB.UploadlabRequestRequest inValue = new Services_All.Jordan_LAB.UploadlabRequestRequest();
            inValue.Body = new Services_All.Jordan_LAB.UploadlabRequestRequestBody();
            inValue.Body.facilityLogin = facilityLogin;
            inValue.Body.facilityPwd = facilityPwd;
            inValue.Body.clinicianLogin = clinicianLogin;
            inValue.Body.clinicianPwd = clinicianPwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            return ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).UploadlabRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Jordan_LAB.UploadLabAuthorizationResponse Services_All.Jordan_LAB.LabValidateTransactionSoap.UploadLabAuthorization(Services_All.Jordan_LAB.UploadLabAuthorizationRequest request) {
            return base.Channel.UploadLabAuthorization(request);
        }
        
        public int UploadLabAuthorization(string PayerLogin, string PayerPwd, byte[] fileContent, string fileName, out string errorMessage, out byte[] errorReport) {
            Services_All.Jordan_LAB.UploadLabAuthorizationRequest inValue = new Services_All.Jordan_LAB.UploadLabAuthorizationRequest();
            inValue.Body = new Services_All.Jordan_LAB.UploadLabAuthorizationRequestBody();
            inValue.Body.PayerLogin = PayerLogin;
            inValue.Body.PayerPwd = PayerPwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            Services_All.Jordan_LAB.UploadLabAuthorizationResponse retVal = ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).UploadLabAuthorization(inValue);
            errorMessage = retVal.Body.errorMessage;
            errorReport = retVal.Body.errorReport;
            return retVal.Body.UploadLabAuthorizationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.UploadLabAuthorizationResponse> Services_All.Jordan_LAB.LabValidateTransactionSoap.UploadLabAuthorizationAsync(Services_All.Jordan_LAB.UploadLabAuthorizationRequest request) {
            return base.Channel.UploadLabAuthorizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.Jordan_LAB.UploadLabAuthorizationResponse> UploadLabAuthorizationAsync(string PayerLogin, string PayerPwd, byte[] fileContent, string fileName) {
            Services_All.Jordan_LAB.UploadLabAuthorizationRequest inValue = new Services_All.Jordan_LAB.UploadLabAuthorizationRequest();
            inValue.Body = new Services_All.Jordan_LAB.UploadLabAuthorizationRequestBody();
            inValue.Body.PayerLogin = PayerLogin;
            inValue.Body.PayerPwd = PayerPwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            return ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).UploadLabAuthorizationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Jordan_LAB.DownloadTransactionFileResponse Services_All.Jordan_LAB.LabValidateTransactionSoap.DownloadTransactionFile(Services_All.Jordan_LAB.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFile(request);
        }
        
        public int DownloadTransactionFile(string login, string pwd, string fileId, out string fileName, out byte[] file, out string errorMessage) {
            Services_All.Jordan_LAB.DownloadTransactionFileRequest inValue = new Services_All.Jordan_LAB.DownloadTransactionFileRequest();
            inValue.Body = new Services_All.Jordan_LAB.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            Services_All.Jordan_LAB.DownloadTransactionFileResponse retVal = ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).DownloadTransactionFile(inValue);
            fileName = retVal.Body.fileName;
            file = retVal.Body.file;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.DownloadTransactionFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.DownloadTransactionFileResponse> Services_All.Jordan_LAB.LabValidateTransactionSoap.DownloadTransactionFileAsync(Services_All.Jordan_LAB.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.Jordan_LAB.DownloadTransactionFileResponse> DownloadTransactionFileAsync(string login, string pwd, string fileId) {
            Services_All.Jordan_LAB.DownloadTransactionFileRequest inValue = new Services_All.Jordan_LAB.DownloadTransactionFileRequest();
            inValue.Body = new Services_All.Jordan_LAB.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            return ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).DownloadTransactionFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Jordan_LAB.GetNewTransactionsResponse Services_All.Jordan_LAB.LabValidateTransactionSoap.GetNewTransactions(Services_All.Jordan_LAB.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactions(request);
        }
        
        public int GetNewTransactions(string login, string pwd, out string xmlTransactions, out string errorMessage) {
            Services_All.Jordan_LAB.GetNewTransactionsRequest inValue = new Services_All.Jordan_LAB.GetNewTransactionsRequest();
            inValue.Body = new Services_All.Jordan_LAB.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            Services_All.Jordan_LAB.GetNewTransactionsResponse retVal = ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).GetNewTransactions(inValue);
            xmlTransactions = retVal.Body.xmlTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetNewTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.GetNewTransactionsResponse> Services_All.Jordan_LAB.LabValidateTransactionSoap.GetNewTransactionsAsync(Services_All.Jordan_LAB.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.Jordan_LAB.GetNewTransactionsResponse> GetNewTransactionsAsync(string login, string pwd) {
            Services_All.Jordan_LAB.GetNewTransactionsRequest inValue = new Services_All.Jordan_LAB.GetNewTransactionsRequest();
            inValue.Body = new Services_All.Jordan_LAB.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).GetNewTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Jordan_LAB.SearchTransactionsResponse Services_All.Jordan_LAB.LabValidateTransactionSoap.SearchTransactions(Services_All.Jordan_LAB.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactions(request);
        }
        
        public int SearchTransactions(string login, string pwd, int direction, string callerLicense, string clinicianLicense, string memberID, System.Nullable<int> LabReferenceNo, int transactionStatus, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount, out string foundTransactions, out string errorMessage) {
            Services_All.Jordan_LAB.SearchTransactionsRequest inValue = new Services_All.Jordan_LAB.SearchTransactionsRequest();
            inValue.Body = new Services_All.Jordan_LAB.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.clinicianLicense = clinicianLicense;
            inValue.Body.memberID = memberID;
            inValue.Body.LabReferenceNo = LabReferenceNo;
            inValue.Body.transactionStatus = transactionStatus;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            Services_All.Jordan_LAB.SearchTransactionsResponse retVal = ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).SearchTransactions(inValue);
            foundTransactions = retVal.Body.foundTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SearchTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.SearchTransactionsResponse> Services_All.Jordan_LAB.LabValidateTransactionSoap.SearchTransactionsAsync(Services_All.Jordan_LAB.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.Jordan_LAB.SearchTransactionsResponse> SearchTransactionsAsync(string login, string pwd, int direction, string callerLicense, string clinicianLicense, string memberID, System.Nullable<int> LabReferenceNo, int transactionStatus, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            Services_All.Jordan_LAB.SearchTransactionsRequest inValue = new Services_All.Jordan_LAB.SearchTransactionsRequest();
            inValue.Body = new Services_All.Jordan_LAB.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.clinicianLicense = clinicianLicense;
            inValue.Body.memberID = memberID;
            inValue.Body.LabReferenceNo = LabReferenceNo;
            inValue.Body.transactionStatus = transactionStatus;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            return ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).SearchTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Jordan_LAB.SetTransactionDownloadedResponse Services_All.Jordan_LAB.LabValidateTransactionSoap.SetTransactionDownloaded(Services_All.Jordan_LAB.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloaded(request);
        }
        
        public int SetTransactionDownloaded(string login, string pwd, string fileID, out string errorMessage) {
            Services_All.Jordan_LAB.SetTransactionDownloadedRequest inValue = new Services_All.Jordan_LAB.SetTransactionDownloadedRequest();
            inValue.Body = new Services_All.Jordan_LAB.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileID = fileID;
            Services_All.Jordan_LAB.SetTransactionDownloadedResponse retVal = ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).SetTransactionDownloaded(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SetTransactionDownloadedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.SetTransactionDownloadedResponse> Services_All.Jordan_LAB.LabValidateTransactionSoap.SetTransactionDownloadedAsync(Services_All.Jordan_LAB.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloadedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.Jordan_LAB.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(string login, string pwd, string fileID) {
            Services_All.Jordan_LAB.SetTransactionDownloadedRequest inValue = new Services_All.Jordan_LAB.SetTransactionDownloadedRequest();
            inValue.Body = new Services_All.Jordan_LAB.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileID = fileID;
            return ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).SetTransactionDownloadedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Jordan_LAB.GetLabTransactionResponse Services_All.Jordan_LAB.LabValidateTransactionSoap.GetLabTransaction(Services_All.Jordan_LAB.GetLabTransactionRequest request) {
            return base.Channel.GetLabTransaction(request);
        }
        
        public int GetLabTransaction(string login, string pwd, string memberId, string nationalId, int LabReferenceNo, out string xmlTransactions, out string errorMessage) {
            Services_All.Jordan_LAB.GetLabTransactionRequest inValue = new Services_All.Jordan_LAB.GetLabTransactionRequest();
            inValue.Body = new Services_All.Jordan_LAB.GetLabTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.memberId = memberId;
            inValue.Body.nationalId = nationalId;
            inValue.Body.LabReferenceNo = LabReferenceNo;
            Services_All.Jordan_LAB.GetLabTransactionResponse retVal = ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).GetLabTransaction(inValue);
            xmlTransactions = retVal.Body.xmlTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetLabTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.GetLabTransactionResponse> Services_All.Jordan_LAB.LabValidateTransactionSoap.GetLabTransactionAsync(Services_All.Jordan_LAB.GetLabTransactionRequest request) {
            return base.Channel.GetLabTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.Jordan_LAB.GetLabTransactionResponse> GetLabTransactionAsync(string login, string pwd, string memberId, string nationalId, int LabReferenceNo) {
            Services_All.Jordan_LAB.GetLabTransactionRequest inValue = new Services_All.Jordan_LAB.GetLabTransactionRequest();
            inValue.Body = new Services_All.Jordan_LAB.GetLabTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.memberId = memberId;
            inValue.Body.nationalId = nationalId;
            inValue.Body.LabReferenceNo = LabReferenceNo;
            return ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).GetLabTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.Jordan_LAB.GetLabListTransactionsResponse Services_All.Jordan_LAB.LabValidateTransactionSoap.GetLabListTransactions(Services_All.Jordan_LAB.GetLabListTransactionsRequest request) {
            return base.Channel.GetLabListTransactions(request);
        }
        
        public int GetLabListTransactions(string login, string pwd, string memberId, string nationalId, out string xmlTransactions, out string errorMessage) {
            Services_All.Jordan_LAB.GetLabListTransactionsRequest inValue = new Services_All.Jordan_LAB.GetLabListTransactionsRequest();
            inValue.Body = new Services_All.Jordan_LAB.GetLabListTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.memberId = memberId;
            inValue.Body.nationalId = nationalId;
            Services_All.Jordan_LAB.GetLabListTransactionsResponse retVal = ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).GetLabListTransactions(inValue);
            xmlTransactions = retVal.Body.xmlTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetLabListTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.Jordan_LAB.GetLabListTransactionsResponse> Services_All.Jordan_LAB.LabValidateTransactionSoap.GetLabListTransactionsAsync(Services_All.Jordan_LAB.GetLabListTransactionsRequest request) {
            return base.Channel.GetLabListTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.Jordan_LAB.GetLabListTransactionsResponse> GetLabListTransactionsAsync(string login, string pwd, string memberId, string nationalId) {
            Services_All.Jordan_LAB.GetLabListTransactionsRequest inValue = new Services_All.Jordan_LAB.GetLabListTransactionsRequest();
            inValue.Body = new Services_All.Jordan_LAB.GetLabListTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.memberId = memberId;
            inValue.Body.nationalId = nationalId;
            return ((Services_All.Jordan_LAB.LabValidateTransactionSoap)(this)).GetLabListTransactionsAsync(inValue);
        }
    }
}
