//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services_All.JenkinsICM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.icm.dhc.com/", ConfigurationName="JenkinsICM.ICMService")]
    public interface ICMService {
        
        // CODEGEN: Generating message contract since the operation proccessTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Services_All.JenkinsICM.proccessTransactionResponse1 proccessTransaction(Services_All.JenkinsICM.proccessTransaction request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Services_All.JenkinsICM.proccessTransactionResponse1> proccessTransactionAsync(Services_All.JenkinsICM.proccessTransaction request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submission : object, System.ComponentModel.INotifyPropertyChanged {
        
        private submissionHeader headerField;
        
        private submissionTransaction[] transactionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public submissionHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public submissionTransaction[] Transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
                this.RaisePropertyChanged("Transaction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string submissionDestinationField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private HeaderDispositionFlag dispositionFlagField;
        
        private string referenceIDField;
        
        private HeaderTransactionType transactionTypeField;
        
        private HeaderProcessType processTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string SubmissionDestination {
            get {
                return this.submissionDestinationField;
            }
            set {
                this.submissionDestinationField = value;
                this.RaisePropertyChanged("SubmissionDestination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
                this.RaisePropertyChanged("SenderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
                this.RaisePropertyChanged("ReceiverID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public HeaderDispositionFlag DispositionFlag {
            get {
                return this.dispositionFlagField;
            }
            set {
                this.dispositionFlagField = value;
                this.RaisePropertyChanged("DispositionFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public HeaderTransactionType transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("transactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public HeaderProcessType processType {
            get {
                return this.processTypeField;
            }
            set {
                this.processTypeField = value;
                this.RaisePropertyChanged("processType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dimensions-healthcare.net/ICM/ICMSchema")]
    public enum HeaderDispositionFlag {
        
        /// <remarks/>
        TEST,
        
        /// <remarks/>
        PRODUCTION,
        
        /// <remarks/>
        PTE_SUBMIT,
        
        /// <remarks/>
        PTE_VALIDATE_ONLY,
        
        /// <remarks/>
        PTE_RESPONSE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dimensions-healthcare.net/ICM/ICMSchema")]
    public enum HeaderTransactionType {
        
        /// <remarks/>
        Claim,
        
        /// <remarks/>
        Remittance,
        
        /// <remarks/>
        PriorRequest,
        
        /// <remarks/>
        Authorization,
        
        /// <remarks/>
        Eligibility,
        
        /// <remarks/>
        FinancialCharge,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dimensions-healthcare.net/ICM/ICMSchema")]
    public enum HeaderProcessType {
        
        /// <remarks/>
        Review,
        
        /// <remarks/>
        Submit,
        
        /// <remarks/>
        Transmit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string payerIDField;
        
        private string providerIDField;
        
        private string healthPlanIDField;
        
        private string payerTransactionReferenceField;
        
        private double transactionGrossField;
        
        private bool transactionGrossFieldSpecified;
        
        private string transactionPatientShareField;
        
        private double transactionNetField;
        
        private bool transactionNetFieldSpecified;
        
        private string transactionPriorAuthorizationIDField;
        
        private submissionTransactionPerson personField;
        
        private submissionTransactionEncounter encounterField;
        
        private submissionTransactionDiagnosis[] diagnosisField;
        
        private submissionTransactionActivity[] activityField;
        
        private submissionTransactionResubmission resubmissionField;
        
        private submissionTransactionScrubbingHint[] scrubbingHintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PayerID {
            get {
                return this.payerIDField;
            }
            set {
                this.payerIDField = value;
                this.RaisePropertyChanged("PayerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
                this.RaisePropertyChanged("ProviderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string HealthPlanID {
            get {
                return this.healthPlanIDField;
            }
            set {
                this.healthPlanIDField = value;
                this.RaisePropertyChanged("HealthPlanID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PayerTransactionReference {
            get {
                return this.payerTransactionReferenceField;
            }
            set {
                this.payerTransactionReferenceField = value;
                this.RaisePropertyChanged("PayerTransactionReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double TransactionGross {
            get {
                return this.transactionGrossField;
            }
            set {
                this.transactionGrossField = value;
                this.RaisePropertyChanged("TransactionGross");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionGrossSpecified {
            get {
                return this.transactionGrossFieldSpecified;
            }
            set {
                this.transactionGrossFieldSpecified = value;
                this.RaisePropertyChanged("TransactionGrossSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TransactionPatientShare {
            get {
                return this.transactionPatientShareField;
            }
            set {
                this.transactionPatientShareField = value;
                this.RaisePropertyChanged("TransactionPatientShare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double TransactionNet {
            get {
                return this.transactionNetField;
            }
            set {
                this.transactionNetField = value;
                this.RaisePropertyChanged("TransactionNet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionNetSpecified {
            get {
                return this.transactionNetFieldSpecified;
            }
            set {
                this.transactionNetFieldSpecified = value;
                this.RaisePropertyChanged("TransactionNetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string TransactionPriorAuthorizationID {
            get {
                return this.transactionPriorAuthorizationIDField;
            }
            set {
                this.transactionPriorAuthorizationIDField = value;
                this.RaisePropertyChanged("TransactionPriorAuthorizationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public submissionTransactionPerson Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
                this.RaisePropertyChanged("Person");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public submissionTransactionEncounter Encounter {
            get {
                return this.encounterField;
            }
            set {
                this.encounterField = value;
                this.RaisePropertyChanged("Encounter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Diagnosis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public submissionTransactionDiagnosis[] Diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
                this.RaisePropertyChanged("Diagnosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Activity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public submissionTransactionActivity[] Activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
                this.RaisePropertyChanged("Activity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public submissionTransactionResubmission Resubmission {
            get {
                return this.resubmissionField;
            }
            set {
                this.resubmissionField = value;
                this.RaisePropertyChanged("Resubmission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScrubbingHint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public submissionTransactionScrubbingHint[] ScrubbingHint {
            get {
                return this.scrubbingHintField;
            }
            set {
                this.scrubbingHintField = value;
                this.RaisePropertyChanged("ScrubbingHint");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionTransactionPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string insuranceMemberNumberField;
        
        private string nationalIDNumberField;
        
        private string birthDateField;
        
        private Gender genderField;
        
        private bool genderFieldSpecified;
        
        private string nameField;
        
        private string policyField;
        
        private string groupField;
        
        private string addressField;
        
        private string weightField;
        
        private string breastFeedingField;
        
        private string weeksOfAmenorrhoeaField;
        
        private string creatinClearanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string InsuranceMemberNumber {
            get {
                return this.insuranceMemberNumberField;
            }
            set {
                this.insuranceMemberNumberField = value;
                this.RaisePropertyChanged("InsuranceMemberNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NationalIDNumber {
            get {
                return this.nationalIDNumberField;
            }
            set {
                this.nationalIDNumberField = value;
                this.RaisePropertyChanged("NationalIDNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
                this.RaisePropertyChanged("GenderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
                this.RaisePropertyChanged("Policy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=9)]
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=10)]
        public string BreastFeeding {
            get {
                return this.breastFeedingField;
            }
            set {
                this.breastFeedingField = value;
                this.RaisePropertyChanged("BreastFeeding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string WeeksOfAmenorrhoea {
            get {
                return this.weeksOfAmenorrhoeaField;
            }
            set {
                this.weeksOfAmenorrhoeaField = value;
                this.RaisePropertyChanged("WeeksOfAmenorrhoea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=12)]
        public string CreatinClearance {
            get {
                return this.creatinClearanceField;
            }
            set {
                this.creatinClearanceField = value;
                this.RaisePropertyChanged("CreatinClearance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dimensions-healthcare.net/ICM/ICMSchema")]
    public enum Gender {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        U,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionTransactionEncounter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string facilityIDField;
        
        private string typeField;
        
        private string startField;
        
        private string endField;
        
        private string startTypeField;
        
        private string endTypeField;
        
        private string eligibilityIDPayerField;
        
        private string transferSourceField;
        
        private string transferDestinationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FacilityID {
            get {
                return this.facilityIDField;
            }
            set {
                this.facilityIDField = value;
                this.RaisePropertyChanged("FacilityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=4)]
        public string StartType {
            get {
                return this.startTypeField;
            }
            set {
                this.startTypeField = value;
                this.RaisePropertyChanged("StartType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=5)]
        public string EndType {
            get {
                return this.endTypeField;
            }
            set {
                this.endTypeField = value;
                this.RaisePropertyChanged("EndType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string EligibilityIDPayer {
            get {
                return this.eligibilityIDPayerField;
            }
            set {
                this.eligibilityIDPayerField = value;
                this.RaisePropertyChanged("EligibilityIDPayer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string TransferSource {
            get {
                return this.transferSourceField;
            }
            set {
                this.transferSourceField = value;
                this.RaisePropertyChanged("TransferSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string TransferDestination {
            get {
                return this.transferDestinationField;
            }
            set {
                this.transferDestinationField = value;
                this.RaisePropertyChanged("TransferDestination");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionTransactionDiagnosis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeTermField;
        
        private DiagnosisType typeField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodeTerm {
            get {
                return this.codeTermField;
            }
            set {
                this.codeTermField = value;
                this.RaisePropertyChanged("CodeTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DiagnosisType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dimensions-healthcare.net/ICM/ICMSchema")]
    public enum DiagnosisType {
        
        /// <remarks/>
        Principal,
        
        /// <remarks/>
        Secondary,
        
        /// <remarks/>
        Admitting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionTransactionActivity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string codeTermField;
        
        private string startField;
        
        private string endField;
        
        private string codeField;
        
        private double quantityField;
        
        private string orderingClinicianField;
        
        private string clinicianField;
        
        private string priorAuthorizationIDField;
        
        private double activityNetField;
        
        private bool activityNetFieldSpecified;
        
        private double activityGrossField;
        
        private bool activityGrossFieldSpecified;
        
        private submissionTransactionActivityActivityPatientShare activityPatientShareField;
        
        private submissionTransactionActivityObservation[] observationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CodeTerm {
            get {
                return this.codeTermField;
            }
            set {
                this.codeTermField = value;
                this.RaisePropertyChanged("CodeTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string OrderingClinician {
            get {
                return this.orderingClinicianField;
            }
            set {
                this.orderingClinicianField = value;
                this.RaisePropertyChanged("OrderingClinician");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Clinician {
            get {
                return this.clinicianField;
            }
            set {
                this.clinicianField = value;
                this.RaisePropertyChanged("Clinician");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PriorAuthorizationID {
            get {
                return this.priorAuthorizationIDField;
            }
            set {
                this.priorAuthorizationIDField = value;
                this.RaisePropertyChanged("PriorAuthorizationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double ActivityNet {
            get {
                return this.activityNetField;
            }
            set {
                this.activityNetField = value;
                this.RaisePropertyChanged("ActivityNet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActivityNetSpecified {
            get {
                return this.activityNetFieldSpecified;
            }
            set {
                this.activityNetFieldSpecified = value;
                this.RaisePropertyChanged("ActivityNetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double ActivityGross {
            get {
                return this.activityGrossField;
            }
            set {
                this.activityGrossField = value;
                this.RaisePropertyChanged("ActivityGross");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActivityGrossSpecified {
            get {
                return this.activityGrossFieldSpecified;
            }
            set {
                this.activityGrossFieldSpecified = value;
                this.RaisePropertyChanged("ActivityGrossSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public submissionTransactionActivityActivityPatientShare ActivityPatientShare {
            get {
                return this.activityPatientShareField;
            }
            set {
                this.activityPatientShareField = value;
                this.RaisePropertyChanged("ActivityPatientShare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Observation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public submissionTransactionActivityObservation[] Observation {
            get {
                return this.observationField;
            }
            set {
                this.observationField = value;
                this.RaisePropertyChanged("Observation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionTransactionActivityActivityPatientShare : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PatientShareType typeField;
        
        private double valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PatientShareType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("ValueSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dimensions-healthcare.net/ICM/ICMSchema")]
    public enum PatientShareType {
        
        /// <remarks/>
        Deductible,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Co-pay")]
        Copay,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionTransactionActivityObservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private ObservationType typeField;
        
        private string codeField;
        
        private string valueField;
        
        private string valueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ObservationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
                this.RaisePropertyChanged("ValueType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dimensions-healthcare.net/ICM/ICMSchema")]
    public enum ObservationType {
        
        /// <remarks/>
        LOINC,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        File,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Universal Dental")]
        UniversalDental,
        
        /// <remarks/>
        Financial,
        
        /// <remarks/>
        Grouping,
        
        /// <remarks/>
        Modifier,
        
        /// <remarks/>
        ERX,
        
        /// <remarks/>
        Result,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionTransactionResubmission : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sequenceField;
        
        private ResubmissionType typeField;
        
        private string commentField;
        
        private byte[] attachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ResubmissionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
                this.RaisePropertyChanged("Attachment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dimensions-healthcare.net/ICM/ICMSchema")]
    public enum ResubmissionType {
        
        /// <remarks/>
        correction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("internal complaint")]
        internalcomplaint,
        
        /// <remarks/>
        legacy,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class submissionTransactionScrubbingHint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string valueField;
        
        private string valueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
                this.RaisePropertyChanged("ValueType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class proccessTransactionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool statusField;
        
        private string msgField;
        
        private proccessTransactionResponseSubmissionResponse submissionResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public proccessTransactionResponseSubmissionResponse SubmissionResponse {
            get {
                return this.submissionResponseField;
            }
            set {
                this.submissionResponseField = value;
                this.RaisePropertyChanged("SubmissionResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class proccessTransactionResponseSubmissionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private proccessTransactionResponseSubmissionResponseHeader headerField;
        
        private proccessTransactionResponseSubmissionResponseTransaction[] transactionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public proccessTransactionResponseSubmissionResponseHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public proccessTransactionResponseSubmissionResponseTransaction[] Transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
                this.RaisePropertyChanged("Transaction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class proccessTransactionResponseSubmissionResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private HeaderDispositionFlag dispositionFlagField;
        
        private string referenceIDField;
        
        private string transactionDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
                this.RaisePropertyChanged("SenderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
                this.RaisePropertyChanged("ReceiverID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public HeaderDispositionFlag DispositionFlag {
            get {
                return this.dispositionFlagField;
            }
            set {
                this.dispositionFlagField = value;
                this.RaisePropertyChanged("DispositionFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class proccessTransactionResponseSubmissionResponseTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string payerIDField;
        
        private string providerIDField;
        
        private string denialCodeField;
        
        private string commentsField;
        
        private proccessTransactionResponseSubmissionResponseTransactionActivity[] activityField;
        
        private proccessTransactionResponseSubmissionResponseTransactionDiagnosis[] diagnosisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PayerID {
            get {
                return this.payerIDField;
            }
            set {
                this.payerIDField = value;
                this.RaisePropertyChanged("PayerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
                this.RaisePropertyChanged("ProviderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DenialCode {
            get {
                return this.denialCodeField;
            }
            set {
                this.denialCodeField = value;
                this.RaisePropertyChanged("DenialCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Activity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public proccessTransactionResponseSubmissionResponseTransactionActivity[] Activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
                this.RaisePropertyChanged("Activity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Diagnosis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public proccessTransactionResponseSubmissionResponseTransactionDiagnosis[] Diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
                this.RaisePropertyChanged("Diagnosis");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class proccessTransactionResponseSubmissionResponseTransactionActivity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string codeField;
        
        private string codeTermField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private double quantityField;
        
        private bool quantityFieldSpecified;
        
        private string orderingClinicianField;
        
        private string clinicianField;
        
        private double grossField;
        
        private bool grossFieldSpecified;
        
        private double netField;
        
        private bool netFieldSpecified;
        
        private proccessTransactionResponseSubmissionResponseTransactionActivityPatientShare patientShareField;
        
        private double paymentAmountField;
        
        private bool paymentAmountFieldSpecified;
        
        private string priorAuthorizationIDField;
        
        private proccessTransactionResponseSubmissionResponseTransactionActivityEdit[] editField;
        
        private proccessTransactionResponseSubmissionResponseTransactionActivityObservation[] observationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CodeTerm {
            get {
                return this.codeTermField;
            }
            set {
                this.codeTermField = value;
                this.RaisePropertyChanged("CodeTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
                this.RaisePropertyChanged("startDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
                this.RaisePropertyChanged("endDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("QuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string orderingClinician {
            get {
                return this.orderingClinicianField;
            }
            set {
                this.orderingClinicianField = value;
                this.RaisePropertyChanged("orderingClinician");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string clinician {
            get {
                return this.clinicianField;
            }
            set {
                this.clinicianField = value;
                this.RaisePropertyChanged("clinician");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double Gross {
            get {
                return this.grossField;
            }
            set {
                this.grossField = value;
                this.RaisePropertyChanged("Gross");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrossSpecified {
            get {
                return this.grossFieldSpecified;
            }
            set {
                this.grossFieldSpecified = value;
                this.RaisePropertyChanged("GrossSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double Net {
            get {
                return this.netField;
            }
            set {
                this.netField = value;
                this.RaisePropertyChanged("Net");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NetSpecified {
            get {
                return this.netFieldSpecified;
            }
            set {
                this.netFieldSpecified = value;
                this.RaisePropertyChanged("NetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public proccessTransactionResponseSubmissionResponseTransactionActivityPatientShare PatientShare {
            get {
                return this.patientShareField;
            }
            set {
                this.patientShareField = value;
                this.RaisePropertyChanged("PatientShare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double paymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
                this.RaisePropertyChanged("paymentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentAmountSpecified {
            get {
                return this.paymentAmountFieldSpecified;
            }
            set {
                this.paymentAmountFieldSpecified = value;
                this.RaisePropertyChanged("paymentAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PriorAuthorizationID {
            get {
                return this.priorAuthorizationIDField;
            }
            set {
                this.priorAuthorizationIDField = value;
                this.RaisePropertyChanged("PriorAuthorizationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Edit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public proccessTransactionResponseSubmissionResponseTransactionActivityEdit[] Edit {
            get {
                return this.editField;
            }
            set {
                this.editField = value;
                this.RaisePropertyChanged("Edit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Observation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public proccessTransactionResponseSubmissionResponseTransactionActivityObservation[] Observation {
            get {
                return this.observationField;
            }
            set {
                this.observationField = value;
                this.RaisePropertyChanged("Observation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class proccessTransactionResponseSubmissionResponseTransactionActivityPatientShare : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class proccessTransactionResponseSubmissionResponseTransactionActivityEdit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string typeField;
        
        private string subTypeField;
        
        private string codeField;
        
        private ActivityEditRank rankField;
        
        private bool rankFieldSpecified;
        
        private string resultCodeField;
        
        private string resultField;
        
        private string commentField;
        
        private string ruleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
                this.RaisePropertyChanged("SubType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ActivityEditRank Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("Rank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RankSpecified {
            get {
                return this.rankFieldSpecified;
            }
            set {
                this.rankFieldSpecified = value;
                this.RaisePropertyChanged("RankSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ruleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
                this.RaisePropertyChanged("ruleName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dimensions-healthcare.net/ICM/ICMSchema")]
    public enum ActivityEditRank {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class proccessTransactionResponseSubmissionResponseTransactionActivityObservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ObservationType typeField;
        
        private string codeField;
        
        private string valueField;
        
        private string valueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ObservationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
                this.RaisePropertyChanged("ValueType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.icm.dhc.com/")]
    public partial class proccessTransactionResponseSubmissionResponseTransactionDiagnosis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeTermField;
        
        private string typeField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodeTerm {
            get {
                return this.codeTermField;
            }
            set {
                this.codeTermField = value;
                this.RaisePropertyChanged("CodeTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class proccessTransaction {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.icm.dhc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Services_All.JenkinsICM.submission submission;
        
        public proccessTransaction() {
        }
        
        public proccessTransaction(Services_All.JenkinsICM.submission submission) {
            this.submission = submission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class proccessTransactionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.icm.dhc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Services_All.JenkinsICM.proccessTransactionResponse proccessTransactionResponse;
        
        public proccessTransactionResponse1() {
        }
        
        public proccessTransactionResponse1(Services_All.JenkinsICM.proccessTransactionResponse proccessTransactionResponse) {
            this.proccessTransactionResponse = proccessTransactionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICMServiceChannel : Services_All.JenkinsICM.ICMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CMServiceClient : System.ServiceModel.ClientBase<Services_All.JenkinsICM.ICMService>, Services_All.JenkinsICM.ICMService {
        
        public CMServiceClient() {
        }
        
        public CMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Services_All.JenkinsICM.proccessTransactionResponse1 Services_All.JenkinsICM.ICMService.proccessTransaction(Services_All.JenkinsICM.proccessTransaction request) {
            return base.Channel.proccessTransaction(request);
        }
        
        public Services_All.JenkinsICM.proccessTransactionResponse proccessTransaction(Services_All.JenkinsICM.submission submission) {
            Services_All.JenkinsICM.proccessTransaction inValue = new Services_All.JenkinsICM.proccessTransaction();
            inValue.submission = submission;
            Services_All.JenkinsICM.proccessTransactionResponse1 retVal = ((Services_All.JenkinsICM.ICMService)(this)).proccessTransaction(inValue);
            return retVal.proccessTransactionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services_All.JenkinsICM.proccessTransactionResponse1> Services_All.JenkinsICM.ICMService.proccessTransactionAsync(Services_All.JenkinsICM.proccessTransaction request) {
            return base.Channel.proccessTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services_All.JenkinsICM.proccessTransactionResponse1> proccessTransactionAsync(Services_All.JenkinsICM.submission submission) {
            Services_All.JenkinsICM.proccessTransaction inValue = new Services_All.JenkinsICM.proccessTransaction();
            inValue.submission = submission;
            return ((Services_All.JenkinsICM.ICMService)(this)).proccessTransactionAsync(inValue);
        }
    }
}
